PragmatechApp/admin/routes.py
import os
from flask import Flask, render_template, url_for, redirect, request, Blueprint
from PragmatechApp import app, user
from PragmatechApp.models import session, AboutPage, QuestionAnswer, Advantage, BannerImg, Package, GuarantiesPage
from PragmatechApp.admin.forms import BannerImgForm, AboutPageForm, QuestionAnswerForm, CardForm, SinglePageBannerImgForm, GuarantiesForm, PackageForm
from werkzeug.utils import secure_filename

admin = Blueprint('admin', __name__, template_folder="templates")

@admin.route('/dashboard')
def index():
    return render_template('admin_layout.html')

# <--------------------------------------- Add Page Banner --------------------------------------------------------->

@admin.route('/dashboard/səhifələr/banner-əlavə-et', methods = ['GET', 'POST'])
def banner_add():
    form = BannerImgForm()
    banner_imgs = session.query(BannerImg).all()
    if form.validate_on_submit():
        uploaded_file = request.files['banner_img']
        banner_file = secure_filename(uploaded_file.filename)
        uploaded_file.save(os.path.join(app.config['UPLOAD_PATH'], banner_file))

        new_banner = BannerImg(banner_img = banner_file, page_name = form.page_name.data)
        session.add(new_banner)
        session.commit()
        return redirect(url_for('admin.banner_add'))
    return render_template('admin_banner_add.html', form=form, banner_imgs=banner_imgs)

@admin.route('/dashboard/səhifələr/banner-sil/<int:id>', methods = ['GET'])
def banner_delete(id):
    selectedData = session.query(BannerImg).get(id)
    session.delete(selectedData)
    session.commit()
    return redirect(url_for('admin.banner_add'))

# <--------------------------------------- Admin About Page --------------------------------------------------------->

# About Banner Section

@admin.route('/dashboard/səhifələr/haqqımızda', methods=['GET', 'POST'])
def about():
    datas = session.query(AboutPage).all()
    questions = session.query(QuestionAnswer).all()
    form = SinglePageBannerImgForm()
    if session.query(AboutPage).get(1):
        pass
    else:
        details = AboutPage(main_text = "Default Text", second_img = "defolt.jpg")
        session.add(details)
        session.commit()
    selectedBanner = session.query(BannerImg).get(1)
    if form.validate_on_submit():
        if form.banner_img.data:
            uploaded_banner_file = request.files['banner_img']
            banner_filename = secure_filename(uploaded_banner_file.filename)
            uploaded_banner_file.save(os.path.join(app.config['UPLOAD_PATH'], banner_filename))
            selectedBanner.banner_img = banner_filename
            session.commit()
        return redirect(url_for('user.about'))
    return render_template('admin_about_page/admin_about.html', form=form, datas=datas, banner_img=selectedBanner, questions=questions)

@admin.route('/dashboard/səhifələr/haqqımızda/Banner-Section/redaktə-et', methods = ['GET', 'POST'])
def about_edit():
    form = AboutPageForm()
    selectedData = session.query(AboutPage).get(1)
    if form.validate_on_submit():
        if form.second_img.data:
            uploaded_second_file = request.files['second_img']
            second_filename = secure_filename(uploaded_second_file.filename)
            uploaded_second_file.save(os.path.join(app.config['UPLOAD_PATH'], second_filename))
            selectedData.second_img = second_filename
        
        selectedData.main_text = form.main_text.data
        session.commit()
        return redirect(url_for('user.about'))
    elif request.method == 'GET':
        form.main_text.data = selectedData.main_text
    return render_template('admin_about_page/admin_about_edit.html', form=form)

# About Question-Answer Section

@admin.route('/dashboard/səhifələr/haqqımızda/Sual-Cavab/əlavə-et', methods = ['GET', 'POST'])
def about_que_add():
    form = QuestionAnswerForm()
    if form.validate_on_submit():
        new_que = QuestionAnswer(question = form.question.data, answer = form.answer.data)
        session.add(new_que)
        session.commit()
        return redirect(url_for('admin.about'))
    return render_template('admin_about_page/admin_about_que.html', form=form)

@admin.route('/dashboard/səhifələr/haqqımızda/Sual-Cavab/redaktə-et/<int:id>', methods = ['GET', 'POST'])
def about_que_edit(id):
    selectedData = session.query(QuestionAnswer).get(id)
    form = QuestionAnswerForm()
    if form.validate_on_submit():
        selectedData.question = form.question.data
        selectedData.answer = form.answer.data
        session.commit()
        return redirect(url_for('admin.about'))
    elif request.method == 'GET':
        form.question.data = selectedData.question
        form.answer.data = selectedData.answer
    return render_template('admin_about_page/admin_about_que.html', form=form)

@admin.route('/dashboard/səhifələr/haqqımızda/Sual-Cavab/sil/<int:id>', methods = ['GET'])
def about_que_delete(id):
    selectedData = session.query(QuestionAnswer).get(id)
    session.delete(selectedData)
    session.commit()
    return redirect(url_for('admin.about'))

# <--------------------------------------- Admin Advantages Page --------------------------------------------------------->

@admin.route('/dashboard/səhifələr/üstünlüklər', methods=['GET', 'POST'])
def advantages():
    form = SinglePageBannerImgForm()
    advantages = session.query(Advantage).all()
    selectedBanner = session.query(BannerImg).get(2)
    if form.validate_on_submit():
        if form.banner_img.data:
            uploaded_banner_file = request.files['banner_img']
            banner_filename = secure_filename(uploaded_banner_file.filename)
            uploaded_banner_file.save(os.path.join(app.config['UPLOAD_PATH'], banner_filename))
            selectedBanner.banner_img = banner_filename
            session.commit()
        return redirect(url_for('user.advantages'))
    return render_template('admin_advantages_page/admin_advantages.html', form=form, banner_img=selectedBanner, advantages=advantages)

@admin.route('/dashboard/səhifələr/üstünlüklər/əlavə-et', methods = ['GET', 'POST'])
def advantage_add():
    form = CardForm()
    if form.validate_on_submit():
        uploaded_file = request.files['card_img']
        svg_file = secure_filename(uploaded_file.filename)
        uploaded_file.save(os.path.join(app.config['UPLOAD_PATH'], svg_file))

        new_adv = Advantage(svg_img = svg_file, title = form.title.data, description = form.description.data)
        session.add(new_adv)
        session.commit()
        return redirect(url_for('admin.advantages'))
    return render_template('admin_card_add.html', form=form)

@admin.route('/dashboard/səhifələr/üstünlüklər/redaktə-et/<int:id>', methods = ['GET', 'POST'])
def advantage_edit(id):
    form = CardForm()
    selectedAdv = session.query(Advantage).get(id)
    if form.validate_on_submit():
        if form.card_img.data:
            uploaded_banner_file = request.files['card_img']
            svg_filename = secure_filename(uploaded_banner_file.filename)
            uploaded_banner_file.save(os.path.join(app.config['UPLOAD_PATH'], svg_filename))
            selectedAdv.svg_img = svg_filename
        selectedAdv.title = form.title.data
        selectedAdv.description = form.description.data
        session.commit()
        return redirect(url_for('admin.advantages'))
    elif request.method == 'GET':
        form.title.data = selectedAdv.title
        form.description.data = selectedAdv.description
    return render_template('admin_card_add.html', form=form)

@admin.route('/dashboard/səhifələr/üstünlüklər/sil/<int:id>', methods = ['GET'])
def advantage_delete(id):
    selectedAdv = session.query(Advantage).get(id)
    session.delete(selectedAdv)
    session.commit()
    return redirect(url_for('admin.advantages'))

# <--------------------------------------- Admin Training Packages Page --------------------------------------------------------->

@admin.route('/dashboard/səhifələr/tədris-paketləri', methods=['GET', 'POST'])
def packages():
    form = SinglePageBannerImgForm()
    packages = session.query(Package).all()
    selectedBanner = session.query(BannerImg).get(3)
    if form.validate_on_submit():
        if form.banner_img.data:
            uploaded_banner_file = request.files['banner_img']
            banner_filename = secure_filename(uploaded_banner_file.filename)
            uploaded_banner_file.save(os.path.join(app.config['UPLOAD_PATH'], banner_filename))
            selectedBanner.banner_img = banner_filename
            session.commit()
        return redirect(url_for('user.packages'))
    return render_template('admin_packages_page/admin_packages.html', form=form, banner_img=selectedBanner, packages=packages)

@admin.route('/dashboard/səhifələr/tədris-paketləri/əlavə-et', methods = ['GET', 'POST'])
def package_add():
    form = PackageForm()
    if form.validate_on_submit():
        uploaded_file = request.files['pack_img']
        pack_file = secure_filename(uploaded_file.filename)
        uploaded_file.save(os.path.join(app.config['UPLOAD_PATH'], pack_file))

        new_pack = Package(pack_img = pack_file, title = form.title.data, description = form.description.data, all_details = form.all_details.data)
        session.add(new_pack)
        new_banner = BannerImg(banner_img = "defolt.jpg", page_name = form.title.data)
        session.add(new_banner)
        session.commit()
        return redirect(url_for('admin.packages'))
    return render_template('admin_packages_page/admin_package_add.html', form=form)

@admin.route('/dashboard/səhifələr/tədris-paketləri/redaktə-et/<int:id>', methods = ['GET', 'POST'])
def package_edit(id):
    form = PackageForm()
    bannerForm = SinglePageBannerImgForm()
    selectedPack = session.query(Package).get(id)
    if form.validate_on_submit():
        if form.pack_img.data:
            uploaded_banner_file = request.files['pack_img']

PragmatechApp/admin/templates/admin_banner_add.html
{% extends 'admin_layout.html' %}
{% block main %}
<h4>Yeni Səhifəyə Banner Şəkili Əlavə Et</h4>
                        <div class="card">
                            <div class="card-body"> 
                                <div class="row">
                                    <div class="col-lg-12">
                                        <form method="POST" action="" novalidate enctype="multipart/form-data" class="default-form"> 
                                            {{ form.hidden_tag() }}
                                            <div class="form-group row">
                                                {{ form.page_name.label(class="col-sm-2 col-form-label text-right") }}
                                                <div class="col-sm-10">
                                                    {% if form.page_name.errors %}
                                                        {{ form.page_name(class="is-invalid form-control") }}
                                                        <div class="invalid-feedback">
                                                            {% for error in form.page_name.errors %}
                                                                <span>{{ error }}</span>
                                                            {% endfor %}
                                                        </div>
                                                    {% else %}
                                                        {{ form.page_name(class="form-control") }}
                                                    {% endif %}
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                {{ form.banner_img.label(class="col-sm-2 col-form-label text-right") }}
                                                {{ form.banner_img(style="margin-left:12px; margin-top:5px;") }}
                                                {% if form.banner_img.errors %}
                                                    {% for error in form.banner_img.errors %}
                                                        <span class="text-danger">{{ error }}</span></br>
                                                    {% endfor %}
                                                {% endif %}
                                            </div>    
                                            <div class="form-group row">
                                                {{ form.submit(class="btn btn-primary", style="margin-left:15px;") }}
                                            </div>                               
                                        </form>
                                    </div>
                                </div>                                                                      
                            </div>
                        </div>

<h4>Banner Əlavə Edilmiş Səhifələr</h4>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card">
                                <div class="card-body">
                                    <div class="table-responsive">
                                        <table class="table table-striped mb-0">
                                            <thead>
                                                <tr>
                                                    <th>#</th>
                                                    <th>Səhifənin Adı</th>
                                                    <th>Banner Şəkili</th>
                                                    <th>Sil</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for banner_img in banner_imgs %}
                                                    <tr>
                                                        <td>{{ banner_img.id }}</td>
                                                        <td>{{ banner_img.page_name }}</td>
                                                        <td>{{ banner_img.banner_img }}</td>
                                                        <td>
                                                            <a href="{{url_for('admin.banner_delete', id = banner_img.id)}}"><i class="fas fa-trash-alt text-danger font-16"></i></a>
                                                        </td>
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div> 
{% endblock %}

PragmatechApp/admin/templates/admin_card_add.html
{% extends 'admin_layout.html' %}
{% block main %}
                        <div class="card">
                            <div class="card-body"> 
                                <div class="row">
                                    <div class="col-lg-12">
                                        <form method="POST" action="" novalidate enctype="multipart/form-data" class="default-form"> 
                                            {{ form.hidden_tag() }}
                                            <div class="form-group row">
                                                {{ form.card_img.label(class="col-sm-2 col-form-label text-right") }}
                                                {{ form.card_img(style="margin-left:12px; margin-top:5px;") }}
                                                {% if form.card_img.errors %}
                                                    {% for error in form.card_img.errors %}
                                                        <span class="text-danger">{{ error }}</span></br>
                                                    {% endfor %}
                                                {% endif %}
                                            </div> 
                                            <div class="form-group row">
                                                {{ form.title.label(class="col-sm-2 col-form-label text-right") }}
                                                <div class="col-sm-10">
                                                    {% if form.title.errors %}
                                                        {{ form.title(class="is-invalid form-control") }}
                                                        <div class="invalid-feedback">
                                                            {% for error in form.title.errors %}
                                                                <span>{{ error }}</span>
                                                            {% endfor %}
                                                        </div>
                                                    {% else %}
                                                        {{ form.title(class="form-control") }}
                                                    {% endif %}
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                {{ form.description.label(class="col-sm-2 col-form-label text-right") }}
                                                <div class="col-sm-10">
                                                    {% if form.description.errors %}
                                                        {{ form.description(class="is-invalid form-control") }}
                                                        <div class="invalid-feedback">
                                                            {% for error in form.description.errors %}
                                                                <span>{{ error }}</span>
                                                            {% endfor %}
                                                        </div>
                                                    {% else %}
                                                        {{ form.description(class="form-control") }}
                                                    {% endif %}
                                                </div>
                                            </div> 
                                            <div class="form-group row">
                                                {{ form.submit(class="btn btn-primary") }}
                                            </div>                                 
                                        </form>
                                    </div>
                                </div>                                                                      
                            </div>
                        </div>
{% endblock %}

PragmatechApp/admin/templates/admin_layout.html
<!DOCTYPE html>
<html lang="az">

    <head>
        <meta charset="utf-8" />
        <title>Pragmatech - Admin Panel</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta content="Pragmatech Admin Panel" name="description" />
        <meta content="" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />

        <!-- App favicon -->
        <link rel="icon" href="{{ url_for('static', filename='admin/images/favicon-pragma.png') }}" type="image/x-icon">

        <!-- App css -->
        <link href="{{ url_for('static', filename='admin/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ url_for('static', filename='admin/css/jquery-ui.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='admin/css/icons.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ url_for('static', filename='admin/css/metisMenu.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ url_for('static', filename='admin/css/app.min.css') }}" rel="stylesheet" type="text/css" />

        <link href="{{ url_for('static', filename='admin/css/jquery-ui.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='admin/css/icons.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ url_for('static', filename='admin/css/metisMenu.min.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ url_for('static', filename='admin/css/app-material.min.css') }}" rel="stylesheet" type="text/css" />
        
        <!-- include summernote css/js -->
        <link href="{{ url_for('static', filename='summernote/summernote.min.css') }}" rel="stylesheet">
    </head>

    <body>
        <!-- leftbar-tab-menu -->
        <div class="leftbar-tab-menu">
            <div class="main-icon-menu">
                <a href="#" class="logo logo-metrica d-block text-center">
                    <span>
                        <img src="{{ url_for('static', filename='admin/images/favicon-pragma.png') }}" alt="logo-small" class="logo-sm">
                    </span>
                </a>
                <nav class="nav">

                    <a href="#PragmatechPages" class="nav-link" data-toggle="tooltip-custom" data-placement="right" title="" data-original-title="Səhifələr" data-trigger="hover">
                        <i data-feather="copy" class="align-self-center menu-icon icon-dual"></i>             
                    </a><!--end MetricaPages--> 

                </nav><!--end nav-->
            </div><!--end main-icon-menu-->

            <div class="main-menu-inner">
                <!-- LOGO -->
                <div class="topbar-left">
                    <a href="#" class="logo">
                        <span>
                            <h3 style="margin-top:24px;">Pragmatech</h3>
                        </span>
                    </a>                    
                </div>
                <!--end logo-->
                <div class="menu-body slimscroll">

                    <div id="PragmatechPages" class="main-icon-menu-pane">
                        <div class="title-box">
                            <h6 class="menu-title">Səhifələr</h6>        
                        </div>
                        <ul class="nav">
                            <li class="nav-item"><a class="nav-link" href="{{ url_for('admin.banner_add') }}">Add Page Banner</a></li>
                            <li class="nav-item"><a class="nav-link" href="{{ url_for('admin.about') }}">Haqqımızda</a></li>
                            <li class="nav-item"><a class="nav-link" href="{{ url_for('admin.advantages') }}">Üstünlüklər</a></li>
                            <li class="nav-item"><a class="nav-link" href="{{ url_for('admin.packages') }}">Tədris Paketləri</a></li>
                            <li class="nav-item"><a class="nav-link" href="{{ url_for('admin.guaranties') }}">Zəmanətlərimiz</a></li>
                        </ul>
                    </div><!-- end Pages -->

                </div><!--end menu-body-->
            </div><!-- end main-menu-inner-->
        </div>
        <!-- end leftbar-tab-menu-->

        <!-- Top Bar Start -->
        <div class="topbar">
            <!-- Navbar -->
            <nav class="navbar-custom">
                <ul class="list-unstyled topbar-nav mb-0">
                    <li>
                        <a href="#">
                            <span class="responsive-logo">
                                <img src="{{ url_for('static', filename='admin/images/favicon-pragma.png') }}" alt="logo-small" class="logo-sm align-self-center" height="34">
                            </span>
                        </a>
                    </li>
                    <li>
                        <button class="button-menu-mobile nav-link">
                            <i data-feather="menu" class="align-self-center"></i>
                        </button>
                    </li>
                </ul>
            </nav>
            <!-- end navbar-->
        </div>
        <!-- Top Bar End -->

        <div class="page-wrapper">

            <!-- Page Content-->
            <div class="page-content-tab">

                <div class="container-fluid">
                    <!-- Page-Title -->
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="page-title-box">
                                {% block main %}{% endblock %}
                            </div><!--end page-title-box-->
                        </div><!--end col-->
                    </div>
                    <!-- end page title end breadcrumb -->
                </div><!-- container -->
                <footer class="footer text-center text-sm-left">
                    &copy; 2020 Pragmatech
                </footer><!--end footer-->
            </div>
            <!-- end page content -->
        </div>
        <!-- end page-wrapper -->




        <!-- jQuery  -->
        <script src="{{ url_for('static', filename='admin/js/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='admin/js/jquery-ui.min.js') }}"></script>
        <script src="{{ url_for('static', filename='admin/js/bootstrap.bundle.min.js') }}"></script>
        <script src="{{ url_for('static', filename='admin/js/metismenu.min.js') }}"></script>
        <script src="{{ url_for('static', filename='admin/js/waves.js') }}"></script>
        <script src="{{ url_for('static', filename='admin/js/feather.min.js') }}"></script>
        <script src="{{ url_for('static', filename='admin/js/jquery.slimscroll.min.js') }}"></script>
        <script src="{{ url_for('static', filename='admin/js/summernote.js') }}"></script>

        <!-- App js -->
        <script src="{{ url_for('static', filename='summernote/summernote.min.js') }}"></script>
        <script src="{{ url_for('static', filename='admin/js/app.js') }}"></script>

    </body>

</html>